;;;; package.lisp

(defpackage #:util
  (:use #:cl)
  (:nicknames #:ut #:u)
  (:export
    :2d-array-to-list
    :>>
    :add
    :add-gng-edge
    :add-gng-node
    :add-new-art-category
    :add-new-column2csv
    :array-to-list
    :average
    :axis-segments
    :before-visual-2D
    :before-visual-3D
    :between-point
    :bezier
    :c2l
    :categorize-art
    :cdr-list-len<
    :cdr-list-len>
    :combine
    :complement-code
    :consistency
    :convolve
    :copy
    :copy-table
    :correlate
    :cosine-distan
    :cosine-similar
    :cosine-similarity
    :count-items
    :csv2hash
    :csv2org
    :defclass*
    :divide1
    :divide-string
    :dot
    :draw-curve
    :draw-polygons
    :draw-scene
    :draw-scene2
    :draw-scene3
    :draw-scene30
    :draw-scene32
    :exagger-node
    :extend-file
    :flatten
    :fuzzy-and
    :generate-bitree
    :get-bezier-points
    :get-consonants
    :get-file
    :get-nearest-gng-nodes
    :get-scene2
    :get-scene3
    :get-scene32
    :get-value-range
    :get-vowels
    :gl-circle
    :gl-polygon
    :gl-rectangle
    :gl-triangle
    :hash-keys
    :hash-values
    :hash2csv
    :hash2lst
    :hash2org
    :hash2plist
    :hash2string
    :hash2weight-lst
    :hsv2rgb
    :inner
    :insert
    :insert-new-gng-node
    :interleave
    :intersect
    :is-sub-list
    :join
    :key-with-value
    :l2c
    :l2s
    :len
    :levenshtein-distance
    :list-depth
    :list-dimensions
    :list-len<
    :list-len>
    :list-to-2d-array
    :list-to-array
    :list2csv
    :list2hash
    :list2set
    :list<
    :list>
    :load-file
    :lst2set
    :make-art
    :make-gng
    :make-som
    :make-sublists
    :max-breadth
    :max-depth
    :max-list
    :move-gng-node
    :new-sigma
    :norm
    :normal-random
    :normalize
    :order-magnitude
    :org2csv
    :org2hash
    :pair-items
    :phi ;;cumulative distribution function http://www.johndcook.com/blog/python_phi/
    :pingpong
    :plist2hash
    :plot-gl
    :pushl
    :py
    :py2cl_list
    :random-choice
    :random-sample
    :random-uniform
    :random-utter
    :random-word
    :randomize
    :range
    :remove-old-gng-edges
    :remove-one
    :rename-key
    :replace*
    :replace-all
    :replace-lst
    :replace-lst0
    :replace-sublist
    :rgb2hsv
    :round-float
    :round-to
    :s-pdf
    :s2l
    :save-file
    :scale-to-01
    :scale-to-n
    :select-best-items
    :sequence-similarity
    :show
    :show-polygons
    :shuffle
    :simplify
    :simplify-list
    :sine-curve
    :som-adjust-nodes
    :som-categorize
    :som-find-bmu
    :som-influence-decay
    :som-learning-rate-decay
    :som-nodes-distance
    :som-radius-decay
    :split
    :squared-distance
    :step-art
    :str2num
    :strengthen
    :subtract
    :t-pdf
    :test-art
    :test-sine-curve
    :train-art
    :train-gng
    :train-som
    :update-art-node
    :vector-mag
    :weaken
    :weighted-random-choice
    ))

